include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_final_locals: true
    always_declare_return_types: true
    avoid_print: true
    unnecessary_late: true
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    directives_ordering: true
    sort_pub_dependencies: false
